FROM openjdk:11

ENV REPOSITORY=/usr/src
ENV PROJECT_NAME=oauth
ENV JAR_DIR=$REPOSITORY/$PROJECT_NAME/build/libs

ENV APPLICATION=oauth-0.0.1-SNAPSHOT.jar
ENV ACTIVE_MODE=develop

COPY . $REPOSITORY/$PROJECT_NAME
WORKDIR $REPOSITORY/$PROJECT_NAME
RUN ./gradlew clean
RUN ./gradlew build
WORKDIR $JAR_DIR

CMD java -jar -Dspring.profiles.active=$ACTIVE_MODE $APPLICATION