spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://somewhere/oauth?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: never
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql

  jackson:
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    com.example.oauth: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace